config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  resources :categories
  resources :posts

  resources :posts do
    resources :comments
  end

  resources :users, only: [:index, :update, :edit]

  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#contact'
  get 'about' => 'pages#about'

end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :image, :image_cache, :remove_image

  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :body, presence: true
  validates :title, presence: true
  # validates :image, presence: true
  mount_uploader :image, ImageUploader

  def self.search(params)
    posts = all # for not existing params args
    posts = posts.where("LOWER(title) like ?", "%#{params[:search].downcase}%") if params[:search]
    posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
  before_action :authenticate_user!, except: [:index, :show]

  # Index action to render all posts
  def index
    @posts = Post.all.order('created_at DESC')
    @posts = Post.search(params).paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # authorize @post
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @comments = Comment.where(post_id: params[:id]).order('created_at DESC')
    @lasts = Post.where(["id < ?", params[:id].to_i]).last(3)
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :category_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => {:multipart => true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, "Categoria*" %>
    <% if @post.new_record? %>
      <%= f.select :category_id, Category.all.map{|category| [category.name.titleize, category.id]}, {:selected => params[:category], :include_blank => false}, {class: "form-control"} %>
    <% else %>
      <div>
        <%= f.select :category_id, Category.all.map{|category| [category.name.titleize, category.id]}, {:selected => @post.category, :include_blank => false}, {class: "form-control", hidden: true} %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editar Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-7 center-block">
  </div>
  <div class="col-md-5 center-block">
    <%= form_tag posts_path, method: :get do %>
      <div class="col-lg-12">
        <div class="input-group">
          <%= text_field_tag :search, "", class: "form-control", placeholder: "Pesquisar titulo ..." %>
          <span class="input-group-btn">
            <%= submit_tag 'Ir', class: 'btn btn-primary' %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>
  </br>
  </br>
<div class="content content-full-width">
  <% @posts.each_with_index do |post, index| %>
    <% if (index.to_i % 2) != 0 %>
      <div class="post-one-column post-one-column-one">
        <div class="post-image"><img src="<%= post.image.url(:list_thumb) %>" alt=""></div>
        <div class="post-info">
          <h3 class="date-and-category"><a href=""><%= post.created_at.strftime('%d de %b de %Y') %></a><a href=""><%= post.category.name %></a></h3>
          <h2 class="heading"><a href=""><%= post.title %></a></h2>
          <div class="post-text">
            <p><%= raw(post.body).truncate(500).html_safe %></p>
          </div>
          <ul class="social-icons">
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;facebook"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;instagram"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;linkedin"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;twitter"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;pinterest"></i></a></li> -->
          </ul>
          <div class="comments-count">
            <p><a href="<%= post_path(post) %>"><%= post.comments.count %> Comentários</a></p>
          </div>
          <div class="divider">
            <%= link_to "Leia - Mais", post_path(post) %>
            <% if user_signed_in? %>
              <% if policy(post).update? %>
                <%= link_to "Editar", edit_post_path(post), class: "btn btn-default" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="post-one-column post-one-column-two">
        <div class="post-image"><img src="<%= post.image.url(:list_thumb) %>" alt=""></div>
        <div class="post-info">
          <h3 class="date-and-category"><a href=""><%= post.created_at.strftime('%d de %b de %Y') %></a><a href=""><%= post.category.name %></a></h3>
          <h2 class="heading"><a href=""><%= post.title %></a></h2>
          <div class="post-text">
            <p><%= raw(post.body).truncate(500).html_safe %></p>
          </div>
          <ul class="social-icons">
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;facebook"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;instagram"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;linkedin"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;twitter"></i></a></li> -->
            <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;pinterest"></i></a></li> -->
          </ul>
          <div class="comments-count">
            <p><a href="<%= post_path(post) %>"><%= post.comments.count %> Comentários</a></p>
          </div>
          <div class="divider">
            <%= link_to "Leia - Mais", post_path(post) %>
            <% if user_signed_in? %>
              <% if policy(post).update? %>
                <%= link_to "Editar", edit_post_path(post), class: "btn btn-default" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-4 center-block">
    </div>
    <div class="col-md-8 center-block">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>
  </div>

  <!-- <div class="pagination"> -->
  <!--   <div class="newer&#45;posts hidden"><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;long&#45;arrow&#45;left"></i>Newer Posts</a></div> -->
  <!--   <div class="older&#45;posts"><a href="index&#45;one&#45;column&#45;2.html#">Older Posts<i class="fa fa&#45;long&#45;arrow&#45;right"></i></a></div> -->
  <!-- </div> -->
</div>
</div>

app/views/posts/new.html.erb
<h2>Criar novo Post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="blog-post-1">
  <h3 class="category"><a href=""><%= @post.category.name %></a></h3>
  <h2 class="heading"> <%= @post.title %></h2>
  <h3 class="date"><a href=""><%= @post.created_at.strftime('%d de %b de %Y') %></a></h3>
  <div class="post-image"><img src="<%= @post.image.url(:content) %>" alt=""></div>
  <div class="post-text">
    <%= raw @post.body.html_safe %>
  </div>
  <ul class="social-icons">
    <li><a href="blog-post-1.html#"><i class="fa fa-facebook"></i></a></li>
    <li><a href="blog-post-1.html#"><i class="fa fa-instagram"></i></a></li>
    <!-- <li><a href="blog&#45;post&#45;1.html#"><i class="fa fa&#45;linkedin"></i></a></li> -->
    <li><a href="blog-post-1.html#"><i class="fa fa-twitter"></i></a></li>
    <!-- <li><a href="blog&#45;post&#45;1.html#"><i class="fa fa&#45;pinterest"></i></a></li> -->
  </ul>
  <!-- <div class="tags"> -->
    <!--   <ul> -->
      <!--     <li><a href="category.html">Lifestyle</a></li> -->
      <!--     <li><a href="category.html">Fashion</a></li> -->
      <!--     <li><a href="category.html">Inspiration</a></li> -->
      <!--   </ul> -->
    <!-- </div> -->

  <!-- <div class="about&#45;author"> -->
    <!--   <h3>About author</h3><img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar&#45;1577909_960_720.png" alt="" class="user&#45;photo"> -->
    <!--   <h4 class="name">Helen Brown</h4> -->
    <!--   <ul class="social&#45;icons"> -->
      <!--     <li><a href="blog&#45;post&#45;1.html#"><i class="fa fa&#45;facebook"></i></a></li> -->
      <!--     <li><a href="blog&#45;post&#45;1.html#"><i class="fa fa&#45;instagram"></i></a></li> -->
      <!--     <li><a href="blog&#45;post&#45;1.html#"><i class="fa fa&#45;linkedin"></i></a></li> -->
      <!--   </ul> -->
    <!--   <p class="text">Lorem ipsum dolor sit amet, utroque sapientem cu per. In mei commodo prompta, sit at atomorum incorrupte. Omnium prodesset cu nam, vim dictas omnesque et.</p> -->
    <!-- </div> -->

  <div class="related-posts">
    <h3>Notícias Relacionadas</h3>
    <% @lasts.each do |last| %>
      <div class="related-post"><img src="<%= last.image.url(:thumb) %>" alt="" class="related-post-image">
        <h3 class="date-and-category"><a href="<%= post_path(last) %>"><%= last.created_at.strftime("%d de %b de %Y") %></a><a href="<%= post_path(last) %>"><%= last.category.name %></a></h3>
        <h2 class="heading"><a href="<%= post_path(last) %>"><%= last.title %></a></h2>
      </div>
    <% end %>
    <!-- <div class="related&#45;post"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa&#45;a19e&#45;4bfe&#45;b380&#45;f6fde1e95daa/fsGJguDnb9sjUg/img/related&#45;post&#45;2.jpg" alt="" class="related&#45;post&#45;image"> -->
      <!--   <h3 class="date&#45;and&#45;category"><a href="date.html">27 March 2016</a><a href="category.html">Inspiration</a></h3> -->
      <!--   <h2 class="heading"><a href="blog&#45;post&#45;1.html">It`s time to change the future</a></h2> -->
      <!-- </div> -->
    <!-- <div class="related&#45;post"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa&#45;a19e&#45;4bfe&#45;b380&#45;f6fde1e95daa/fsGJguDnb9sjUg/img/related&#45;post&#45;3.jpg" alt="" class="related&#45;post&#45;image"> -->
      <!--   <h3 class="date&#45;and&#45;category"><a href="date.html">27 March 2016</a><a href="category.html">Inspiration</a></h3> -->
      <!--   <h2 class="heading"><a href="blog&#45;post&#45;1.html">Never stop  dreaming</a></h2> -->
      <!-- </div> -->
  </div>

  <% if current_user.present? %>
    <div class="leave-a-reply">
      <%= render 'comments/form'%>
    </div>
  <% else %>
    <div class="alert alert-info">
      <strong>OBS:</strong> Apenas usuários logados podem criar comentários
    </div>
  <% end %>
  <div id="comments" class="comments">
    <h3><%= (@comments.count < 2) ? 'Comentário' : 'Comentários' %></h3>
    <% @comments.each do |comment| %>
      <div class="comment">
        <% if comment.user.image.present? %>
          <img src="<%= comment.user.image %>" alt="" class="user-photo">
        <% else %>
          <img src="https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" alt="" class="user-photo">
        <% end %>

        <% if user_signed_in? %>
          <% if current_user.admin? || (comment.user.id == current_user.id) %>
            <h3 class="name"><%= comment.user.name %></h3><a href="blog-post-1.html#" class="reply">X</a>
          <% end %>
        <% end %>
        <h4 class="date"><%= comment.created_at.strftime("%d de %b de %Y as %H.%M ") %></h4>
        <p class="text"><%= comment.body %></p>
        <!-- <div class="comment comment&#45;replay"> -->
          <!--   <!&#45;&#45; <img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa&#38;#45;a19e&#38;#45;4bfe&#38;#45;b380&#38;#45;f6fde1e95daa/fsGJguDnb9sjUg/img/user&#38;#45;photo&#38;#45;2.jpg" alt="" class="user&#38;#45;photo"> &#45;&#45;> -->
          <!--   <h3 class="name">Helen Brown</h3><a href="blog&#45;post&#45;1.html#" class="reply">Reply</a> -->
          <!--   <h4 class="date">27 March 2016 at  3.44 pm</h4> -->
          <!--   <p class="text">Lorem ipsum dolor sit amet, utroque sapientem cu per. In mei commodo prompta, sit at atom incorrupte. Omnium prodesset cu nam, vim dictas omnesque et.</p> -->
          <!-- </div> -->
      </div>
    <% end %>

  </div>
</div>