config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  resources :categories
  resources :posts

  resources :posts do
    resources :comments
  end

  resources :users, only: [:index, :update, :edit]

  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#contact'
  get 'about' => 'pages#about'

end

app/views/layouts/_footer.html.erb
<!-- START: Instagram-->
    <div class="instagram">
      <h3>Follow on instagram</h3>
      <ul>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-1.jpeg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-2.jpg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-3.jpeg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-4.jpg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-5.jpeg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-6.jpg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-7.jpeg" alt/></a></li>
        <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/inst-8.jpg" alt/></a></li>
      </ul>
    </div>
    <!-- END: Instagram-->
    <!-- START: Footer-->
    <div class="footer">
      <div class="container">
        <p class="copyright">&copy; 2016 All rights reserved</p>
        <ul class="social-icons">
          <li><a href="index.html#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="index.html#"><i class="fa fa-instagram"></i></a></li>
          <li><a href="index.html#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="index.html#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="index.html#"><i class="fa fa-pinterest"></i></a></li>
        </ul>
      </div>
    </div>
    <!-- END: Footer-->

app/views/layouts/_menu.html.erb
<div id="menu" class="menu">
  <div class="container">
    <ul class="social-icons">
      <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;facebook"></i></a></li> -->
      <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;instagram"></i></a></li> -->
      <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;linkedin"></i></a></li> -->
      <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;twitter"></i></a></li> -->
      <!-- <li><a href="index&#45;one&#45;column&#45;2.html#"><i class="fa fa&#45;pinterest"></i></a></li> -->
    </ul>
    <ul class="navigation">
      <li><a href="<%= posts_path %>">Início</a></li>
      <li><a href="">Notícias<i class="fa fa-angle-down"></i></a>
        <ul>
          <li><a href="<%= new_post_path %>">Nova</a></li>
          <li><a href="index-list.html">Lista</a></li>
        </ul>
      </li>
      <li><a href="">Usuários<i class="fa fa-angle-down"></i></a>
        <ul>
          <li><a href="<%= new_user_registration_path %>">Novo</a></li>
          <li><a href="<%= users_path %>">Lista</a></li>
        </ul>
      </li>
      <li><a href="">Categorias<i class="fa fa-angle-down"></i></a>
        <ul>
          <li><a href="<%= new_category_path %>">Nova</a></li>
          <li><a href="<%= categories_path %> ">Lista</a></li>
        </ul>
      </li>
      <li><a href="Sobre.html">Sobre</a></li>
      <li><a href="Contato.html">Contatos</a></li>
      <% if current_user.present? %>
        <li><a href="#"><%= current_user.to_s %><i class="fa fa-angle-down"></i></a>
          <ul>
            <li><%= link_to('Editar', destroy_user_session_path, :method => :delete) %></li>
            <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to('Login', new_user_session_path)  %></li>
      <% end %>
    </ul>
    <div class="menu-tougle">
      <div class="bar"></div>
      <div class="bar"></div>
      <div class="bar"></div>
    </div>
  </div>
</div>

app/views/layouts/_menu_left.html.erb
<div class="menu-sidebar-disable"></div>
<div class="menu-sidebar">
  <div class="exit"><i class="fa fa-close"></i></div>
  <div class="form search">
    <input type="search" placeholder="Search"/><i class="fa fa-search"></i>
  </div>
  <ul class="navigation">
    <li><a href="index.html">Home</a>
      <ul>
        <li><a href="index.html">Home Default</a></li>
        <li><a href="index-list.html">Home List</a></li>
        <li><a href="index-one-column-1.html">Home One Column 1</a></li>
        <li><a href="index-one-column-2.html">Home One Column 2</a></li>
        <li><a href="index-two-columns-1.html">Home Two Columns 1</a></li>
        <li><a href="index-two-columns-2.html">Home Two Columns 2</a></li>
        <li><a href="index-three-columns.html">Home Three Columns</a></li>
        <li><a href="index-without-hero.html">Home Without Hero</a></li>
      </ul>
    </li>
    <li><a href="blog-post-1.html">Post</a>
      <ul>
        <li><a href="blog-post-1.html">Post 1</a></li>
        <li><a href="blog-post-2.html">Post 2</a></li>
        <li><a href="blog-post-3.html">Post 3</a></li>
        <li><a href="features.html">Features</a></li>
      </ul>
    </li>
    <li><a href="category.html">Lifestyle</a></li>
    <li><a href="category.html">Travel</a></li>
    <li><a href="about.html">About</a></li>
    <li><a href="contact.html">Contact</a></li>
  </ul>
  <div class="about-me">
    <h3><a href="about.html">About Me</a></h3>
    <div class="photo"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/photo.jpg" alt/></div>
    <p>Hi, my name is Jane Doe. I am traveler, writer and blogger.  Lorem ipsum dolor sit amet, te consectetursit at atomorum</p>
  </div>
  <div class="follow-me">
    <h3>Follow me</h3>
    <ul class="social-icons">
      <li><a href="index.html#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-instagram"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-linkedin"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-twitter"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-pinterest"></i></a></li>
    </ul>
    <div class="banner-spot"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/banner-spot.jpg" alt/></div>
  </div>
  <div class="subscribe">
    <h3>Subscribe</h3>
    <p>Enter your email address to subscribe to this blog and receive notifications of new posts by email.</p>
    <form>
      <input type="email" placeholder="Enter your email"/>
      <input type="submit" value="submit"/>
    </form>
  </div>
  <ul class="footer-links">
    <li><a href="index.html#">Help</a></li>
    <li><a href="index.html#">Terms</a></li>
    <li><a href="index.html#">Privacy</a></li>
    <li><a href="index.html#">Advertise</a></li>
  </ul>
</div>

app/views/layouts/_sidebar.html.erb
<!-- START: Sidebar-->
<div class="sidebar">
  <div class="about-me">
    <h3><a href="about.html">About Me</a></h3>
    <div class="photo"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/photo.jpg" alt/></div>
    <p>Hi, my name is Jane Doe. I am traveler, writer and blogger.  Lorem ipsum dolor sit amet, te consectetursit at atomorum</p>
  </div>
  <div class="follow-me">
    <h3>Follow me</h3>
    <ul class="social-icons">
      <li><a href="index.html#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-instagram"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-linkedin"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-twitter"></i></a></li>
      <li><a href="index.html#"><i class="fa fa-pinterest"></i></a></li>
    </ul>
    <div class="banner-spot"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/banner-spot.jpg" alt/></div>
  </div>
  <div class="subscribe">
    <h3>Subscribe</h3>
    <p>Enter your email address to subscribe to this blog and receive notifications of new posts by email.</p>
    <form>
      <input type="email" placeholder="Enter your email"/>
      <input type="submit" value="submit"/>
    </form>
  </div>
  <div class="popular-posts">
    <h3>Popular posts</h3>
    <div class="pop-post"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/popular-post-1.jpeg" alt/>
      <div class="info">
        <h4><a href="date.html">27 March 2016</a></h4>
        <h3><a href="blog-post-1.html">Does happiness realy exist</a></h3>
      </div>
    </div>
    <div class="pop-post"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/popular-post-2.jpg" alt/>
      <div class="info">
        <h4><a href="date.html">27 March 2016</a></h4>
        <h3><a href="blog-post-1.html">Be honest with yourself</a></h3>
      </div>
    </div>
    <div class="pop-post"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/popular-post-3.jpg" alt/>
      <div class="info">
        <h4><a href="date.html">27 March 2016</a></h4>
        <h3><a href="blog-post-1.html">Things that inspire me the most</a></h3>
      </div>
    </div>
  </div>
  <div class="categories">
    <h3>Categories</h3>
    <div class="category">
      <h3><a href="category.html">Lifestyle</a></h3>
      <p>42 Posts</p>
    </div>
    <div class="category">
      <h3><a href="category.html">Inspiration</a></h3>
      <p>57 Posts</p>
    </div>
    <div class="category">
      <h3><a href="category.html">Travel</a></h3>
      <p>32 Posts</p>
    </div>
  </div>
  <div class="tags">
    <h3>Tags</h3>
    <ul>
      <li><a href="category.html">Lifestyle</a></li>
      <li><a href="category.html">Fashion</a></li>
      <li><a href="category.html">Inspiration</a></li>
      <li><a href="category.html">Travel</a></li>
      <li><a href="category.html">Movies</a></li>
      <li><a href="category.html">Health</a></li>
    </ul>
  </div>
  <div class="instagram-sidebar">
    <h3>Instagram</h3>
    <ul>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-1.jpeg" alt/></a></li>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-2.jpg" alt/></a></li>
      <li><a href="https://octrace-selena.aerobatic.io/3"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-3.jpeg" alt/></a></li>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-4.jpg" alt/></a></li>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-5.jpeg" alt/></a></li>
      <li><a href="https://octrace-selena.aerobatic.io/3"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-6.jpg" alt/></a></li>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-7.jpeg" alt/></a></li>
      <li><a href="index.html#"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-8.jpg" alt/></a></li>
      <li><a href="https://octrace-selena.aerobatic.io/3"><img src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/img/instagram-sidebar-9.jpg" alt/></a></li>
    </ul>
  </div>
</div>
<!-- END: Sidebar-->

app/views/layouts/_slide.html.erb
<!-- START: Hero-->
<div class="hero">
  <div class="container">
    <div class="carousel carousel-default">
      <% @posts[0..3].each do |post| %>
        <div style="background-image: url(<%= post.image.url(:content) %>);" class="slide">
          <div class="slide-info">
            <!-- <h3 class="category"><a href="category.html">Lifestyle</a></h3> -->
            <h2 class="heading"><a href="blog-post-1.html"><%= post.title %></a></h2>
            <h3 class="date"><a href="date.html"><%= post.created_at.strftime('%d de %b de %Y ') %></a></h3>
          </div>
        </div>
      <% end  %>
    </div>
  </div>
</div>
<!-- END: Hero-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <!-- START: Styles-->
    <link rel="stylesheet" href="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/style.css"/>
    <link rel="stylesheet" href="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/css/adaptive.css"/>
    <link rel="stylesheet" href="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/css/font-awesome.css"/>
    <link rel="stylesheet" href="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/css/owl.carousel.css"/>
    <!-- END: Styles-->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- START: Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,600" rel="stylesheet" type="text/css"/>
    <!-- END: Fonts-->
    <script>__4front__=__aerobatic__={"versionId":"fsGJguDnb9sjUg","versionName":"v3","buildType":"release","webPagePath":"index.html","staticAssetPath":"//d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg","appId":"2ca34baa-a19e-4bfe-b380-f6fde1e95daa","appName":"octrace-selena","appUrl":"https://octrace-selena.aerobatic.io","deployStage":"production","statusCode":200,"manifestSha":"9ba4a50f91379e7c88ae3126e40dd60b1b923aee","baseUrl":"https://octrace-selena.aerobatic.io","versionCommit":"87fd16327b3b4c493a1559ff22785acab2633903"};</script>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body style="height: auto;">
    <!-- START: Header-->
    <div class="header" style="padding-bottom: 0px;">
      <div class="container">
        <h1 class="logo">Banner</h1>
      </div>
    </div>
    <!-- END: Header-->
    <!-- START: Menu-->
    <div id="menu" class="menu">
      <div class="container">
        <ul class="social-icons">
          <li><a href="index-one-column-2.html#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-instagram"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-pinterest"></i></a></li>
        </ul>
        <ul class="navigation">
          <li><a href="<%= posts_path %>">Início</a></li>
          <li><a href="">Notícias<i class="fa fa-angle-down"></i></a>
            <ul>
              <% if current_user.present? %>
                <% unless current_user.comun? %>
                  <li><a href="<%= new_post_path %>">Nova</a></li>
                <% end %>
              <% end %>
              <li><a href="index-list.html">Lista</a></li>
            </ul>
          </li>
          <% if current_user.present? %>
            <% if current_user.admin? %>
              <li><a href="">Usuários<i class="fa fa-angle-down"></i></a>
                <ul>
                  <li><a href="<%= new_user_registration_path %>">Novo</a></li>
                  <li><a href="<%= users_path %>">Lista</a></li>
                </ul>
              </li>
            <% end %>
          <% end %>
          <li><a href="">Categorias<i class="fa fa-angle-down"></i></a>
            <ul>
              <% if current_user.present? %>
                <% unless current_user.comun? %>
                  <li><a href="<%= new_category_path %>">Nova</a></li>
                <% end %>
              <% end %>
              <li><a href="<%= categories_path %> ">Lista</a></li>
            </ul>
          </li>
          <li><a href="<%= contact_path %>">Contato</a></li>
          <% if current_user.present? %>
            <li><a href="#"><%= current_user.to_s %><i class="fa fa-angle-down"></i></a>
              <ul>
                <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path)  %></li>
          <% end %>
        </ul>
        <div class="menu-tougle">
          <div class="bar"></div>
          <div class="bar"></div>
          <div class="bar"></div>
        </div>
      </div>
    </div>
    <!-- END: Menu-->
    <!-- START: Hero-->
    <!-- END: Hero-->
    <div class="main-section">
      <div class="container">
        <div class="content content-full-width">
          <!-- START: Content-->
          <%= yield %>
          <!-- END: Content-->
        </div>
      </div>
    </div>
    <!-- START: Footer-->
    <div class="footer">
      <div class="container">
        <p class="copyright">© 2017 All rights reserved</p>
        <ul class="social-icons">
          <li><a href="index-one-column-2.html#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-instagram"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="index-one-column-2.html#"><i class="fa fa-pinterest"></i></a></li>
        </ul>
      </div>
    </div>
    <!-- END: Footer-->
    <!-- START: Menu Sidebar-->
    <%= render 'layouts/menu_left' %>
    <!-- END: Menu Sidebar-->
    <!-- START: Scripts-->
    <script src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/js/jquery-2.2.4.js"></script>
    <script src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/js/owl.carousel.js"></script>
    <script src="https://d2q4nobwyhnvov.cloudfront.net/2ca34baa-a19e-4bfe-b380-f6fde1e95daa/fsGJguDnb9sjUg/js/main.js"></script>
    <!-- END: Scripts-->
  </body>
</html>